$kind: environment
name: Production
values:
  - key: baseUrl
    value: 'https://your-production-domain.com'
    enabled: true
  - key: platform
    value: dip
    enabled: true
  - key: adminPassword
    value: ''
    enabled: true
    secret: true
  - key: supervisorId
    value: ''
    enabled: true
  - key: loginId
    value: ''
    enabled: true
  - key: cohortId
    value: ''
    enabled: true
  - key: groundId
    value: ''
    enabled: true
  - key: contentId
    value: ''
    enabled: true
  - key: inviteCode
    value: ''
    enabled: true
  - key: inviteLinkId
    value: ''
    enabled: true
  - key: supervisorUuid
    value: ''
    enabled: true
  - key: token
    value: ''
    enabled: true
  - key: username
    value: ''
    enabled: true
  - key: originVerifyKey
    value: 01bde452-415d-4107-87e8-c36fa9747f52
    enabled: true
    secret: true
