import { NextResponse } from 'next/server';
import { Resend } from 'resend';

export const dynamic = 'force-dynamic';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: Request) {
  const { to, type, cv, cover } = await request.json();
  if (!to || !type || !cv) return NextResponse.json({ error: 'Missing fields' }, { status: 400 });
  if (!process.env.RESEND_API_KEY) return NextResponse.json({ error: 'Email not configured' }, { status: 503 });

  const isCv = type === 'cv';
  const subject = isCv
    ? `Your CV — ${cv.fullName || 'Work Readiness Program'}`
    : `Your Cover Letter — ${cover?.role || 'Work Readiness Program'}`;

  const cvHtml = `
    <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:40px;color:#111;font-size:13px;line-height:1.6;">
      <div style="border-bottom:2px solid #111;padding-bottom:12px;margin-bottom:16px;">
        <h1 style="margin:0;font-size:22px;font-weight:700;">${cv.fullName || ''}</h1>
        <p style="margin:4px 0 0;color:#555;font-size:12px;">
          ${[cv.phone, cv.email, cv.linkedin, cv.city].filter(Boolean).join(' &nbsp;|&nbsp; ')}
        </p>
      </div>
      ${cv.summary ? `<div style="margin-bottom:16px;"><h2 style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2px;border-bottom:1px solid #ccc;padding-bottom:4px;margin-bottom:8px;">Professional Summary</h2><p>${cv.summary}</p></div>` : ''}
      ${cv.skills ? `<div style="margin-bottom:16px;"><h2 style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2px;border-bottom:1px solid #ccc;padding-bottom:4px;margin-bottom:8px;">Core Skills</h2><p>${cv.skills}</p></div>` : ''}
      ${cv.experience?.some((e: any) => e.title || e.company) ? `
        <div style="margin-bottom:16px;">
          <h2 style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2px;border-bottom:1px solid #ccc;padding-bottom:4px;margin-bottom:8px;">Work Experience</h2>
          ${cv.experience.map((exp: any) => `
            <div style="margin-bottom:12px;">
              <div style="display:flex;justify-content:space-between;">
                <strong>${exp.title}</strong>
                <span style="color:#666;font-size:11px;">${exp.startDate}${exp.startDate ? ' – ' : ''}${exp.current ? 'Present' : exp.endDate}</span>
              </div>
              <div style="color:#555;font-style:italic;">${exp.company}</div>
              <ul style="margin:4px 0 0 16px;padding:0;">${exp.bullets.filter((b: string) => b.trim()).map((b: string) => `<li>${b}</li>`).join('')}</ul>
            </div>
          `).join('')}
        </div>
      ` : ''}
      ${cv.education?.some((e: any) => e.qualification) ? `
        <div style="margin-bottom:16px;">
          <h2 style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2px;border-bottom:1px solid #ccc;padding-bottom:4px;margin-bottom:8px;">Education</h2>
          ${cv.education.map((ed: any) => `<div style="display:flex;justify-content:space-between;margin-bottom:4px;"><span><strong>${ed.qualification}</strong>${ed.institution ? ` — ${ed.institution}` : ''}</span><span style="color:#666;font-size:11px;">${ed.year}</span></div>`).join('')}
        </div>
      ` : ''}
      ${cv.certifications ? `<div style="margin-bottom:16px;"><h2 style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2px;border-bottom:1px solid #ccc;padding-bottom:4px;margin-bottom:8px;">Certifications & Courses</h2><p style="white-space:pre-line;">${cv.certifications}</p></div>` : ''}
      <hr style="margin-top:32px;border:none;border-top:1px solid #eee;" />
      <p style="color:#aaa;font-size:11px;text-align:center;margin-top:12px;">Generated by WeThinkCode_ Work Readiness Program</p>
    </div>`;

  const today = new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' });
  const coverHtml = `
    <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:40px;color:#111;font-size:13px;line-height:1.8;">
      <p style="margin-bottom:4px;"><strong>${cv.fullName || ''}</strong></p>
      ${cv.phone ? `<p style="margin:0;">${cv.phone}</p>` : ''}
      ${cv.email ? `<p style="margin:0;">${cv.email}</p>` : ''}
      ${cv.city ? `<p style="margin:0;">${cv.city}</p>` : ''}
      <p style="margin:24px 0 4px;">${today}</p>
      <p style="margin:0;"><strong>${cover?.recipientName || 'Hiring Manager'}</strong></p>
      <p style="margin:0;">${cover?.company || ''}</p>
      <p style="margin:24px 0;">Dear ${cover?.recipientName || 'Hiring Manager'},</p>
      <p style="margin-bottom:16px;">I am writing to express my strong interest in the <strong>${cover?.role || '[Role]'}</strong> position at <strong>${cover?.company || '[Company]'}</strong>. ${cover?.whyRole || ''}</p>
      ${cover?.whyCompany ? `<p style="margin-bottom:16px;">${cover.whyCompany}</p>` : ''}
      ${cover?.keyStrength ? `<p style="margin-bottom:16px;">${cover.keyStrength}</p>` : ''}
      <p style="margin-bottom:16px;">I have attached my CV for your consideration and would welcome the opportunity to discuss how my background aligns with your team's needs. Please feel free to contact me at ${cv.phone || '[phone]'} or ${cv.email || '[email]'}.</p>
      <p style="margin-bottom:24px;">Thank you for your time and consideration.</p>
      <p>Kind regards,</p>
      <p style="margin-top:24px;"><strong>${cv.fullName || ''}</strong></p>
      <hr style="margin-top:32px;border:none;border-top:1px solid #eee;" />
      <p style="color:#aaa;font-size:11px;text-align:center;margin-top:12px;">Generated by WeThinkCode_ Work Readiness Program</p>
    </div>`;

  try {
    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev',
      to,
      subject,
      html: isCv ? cvHtml : coverHtml,
    });
    return NextResponse.json({ success: true });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
