import { NextResponse } from 'next/server';
import { sendEmail } from '@/lib/email';

export const dynamic = 'force-dynamic';

export async function POST(request: Request) {
  const { to, type, cv, cover, pdfBase64, filename } = await request.json();
  if (!to || !type || !cv) return NextResponse.json({ error: 'Missing fields' }, { status: 400 });
  if (!process.env.WTC_EMAIL_API_KEY) return NextResponse.json({ error: 'Email not configured' }, { status: 503 });

  const isCv = type === 'cv';
  const docName = isCv ? 'CV' : 'Cover Letter';
  const subject = isCv
    ? `Your CV — ${cv.fullName || 'Work Readiness Program'}`
    : `Your Cover Letter — ${cover?.role || 'Work Readiness Program'}`;

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/></head>
<body style="margin:0;padding:0;background:#f5f7fa;">
    <div style="font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;max-width:520px;margin:40px auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;box-shadow:0 4px 6px -1px rgba(0, 0, 0, 0.1);">
      <div style="height:4px;background:#0047AB;"></div>
      <div style="padding:32px;">
        <p style="color:#0047AB;font-size:12px;letter-spacing:2px;text-transform:uppercase;margin:0 0 16px 0;font-weight:600;">WeThinkCode_ Work Readiness Program</p>
        <h2 style="color:#0f172a;font-size:20px;margin:0 0 12px 0;">Your ${docName} is attached</h2>
        <p style="color:#334155;font-size:14px;line-height:1.8;margin:0 0 20px 0;">
          Hi ${cv.fullName || 'there'},<br/><br/>
          Your <strong style="color:#0f172a;">${docName}</strong> is attached to this email as a PDF.
          You can download it, print it, or attach it directly to job applications.
        </p>
        <div style="background:#f1f5f9;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin-bottom:20px;">
          <p style="color:#475569;font-size:12px;margin:0;line-height:1.6;">
            <strong style="color:#0f172a;">Tips:</strong><br/>
            • Save the PDF to your phone or Google Drive for easy access<br/>
            • Attach it to job applications — never paste your CV into the email body<br/>
            • Update your CV every time you gain new experience
          </p>
        </div>
        <p style="color:#64748b;font-size:12px;margin:0;">Generated by WeThinkCode_ Work Readiness Program</p>
      </div>
    </div>
</body>
</html>`;

  try {
    const emailPayload: any = { 
      to_email: to, 
      subject, 
      message_html: html 
    };

    // Attach PDF if provided
    if (pdfBase64 && filename) {
      emailPayload.attachments = [{
        filename,
        content: pdfBase64,
      }];
    }

    await sendEmail(emailPayload);

    return NextResponse.json({ success: true });
  } catch (e: any) {
    console.error('Send document exception:', e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
