import { NextResponse } from 'next/server';
import { sendEmail } from '@/lib/email';

export const dynamic = 'force-dynamic';

export async function POST(request: Request) {
  const { to, type, cv, cover, pdfBase64, filename } = await request.json();
  if (!to || !type || !cv) return NextResponse.json({ error: 'Missing fields' }, { status: 400 });
  if (!process.env.WTC_EMAIL_API_KEY) return NextResponse.json({ error: 'Email not configured' }, { status: 503 });

  const isCv = type === 'cv';
  const docName = isCv ? 'CV' : 'Cover Letter';
  const subject = isCv
    ? `Your CV — ${cv.fullName || 'Work Readiness Program'}`
    : `Your Cover Letter — ${cover?.role || 'Work Readiness Program'}`;

  const html = `
    <div style="font-family:'Courier New',monospace;max-width:520px;margin:40px auto;background:#000;border:1px solid #222;border-radius:12px;overflow:hidden;">
      <div style="height:3px;background:linear-gradient(to right,#00ff9d,#00b0f0,#00ff9d);"></div>
      <div style="padding:32px;">
        <p style="color:#00ff9d;font-size:11px;letter-spacing:3px;text-transform:uppercase;margin:0 0 16px 0;">WeThinkCode_ Work Readiness Program</p>
        <h2 style="color:#fff;font-size:20px;margin:0 0 12px 0;">Your ${docName} is attached</h2>
        <p style="color:#b0b0b0;font-size:14px;line-height:1.8;margin:0 0 20px 0;">
          Hi ${cv.fullName || 'there'},<br/><br/>
          Your <strong style="color:#fff;">${docName}</strong> is attached to this email as a PDF.
          You can download it, print it, or attach it directly to job applications.
        </p>
        <div style="background:#0d0d0d;border:1px solid #1a1a1a;border-radius:8px;padding:16px;margin-bottom:20px;">
          <p style="color:#555;font-size:12px;margin:0;line-height:1.6;">
            Tips:<br/>
            • Save the PDF to your phone or Google Drive for easy access<br/>
            • Attach it to job applications — never paste your CV into the email body<br/>
            • Update your CV every time you gain new experience
          </p>
        </div>
        <p style="color:#444;font-size:12px;margin:0;">Generated by WeThinkCode_ Work Readiness Program</p>
      </div>
      <div style="height:3px;background:linear-gradient(to right,#00ff9d,#00b0f0,#00ff9d);"></div>
    </div>`;

  try {
    const emailPayload: any = { 
      to_email: to, 
      subject, 
      message_html: html 
    };

    // Attach PDF if provided
    if (pdfBase64 && filename) {
      emailPayload.attachments = [{
        filename,
        content: pdfBase64,
      }];
    }

    await sendEmail(emailPayload);

    return NextResponse.json({ success: true });
  } catch (e: any) {
    console.error('Send document exception:', e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
